# Generated by Django 4.0.2 on 2022-02-14 13:09

import re

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='дата регистрации компании')),
                ('slug', models.SlugField(blank=True, max_length=255, unique_for_date='created', validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('owner', models.OneToOneField(help_text='Владелец', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=50, unique=True)),
                ('medicine_category', models.CharField(choices=[('Pills', 'Pills'), ('Liquids', 'Liquids'), ('Injections', 'Injections')], help_text='Тип лекарства', max_length=10)),
                ('description', models.TextField(help_text='Описание', max_length=255)),
                ('release_date', models.DateField(help_text='Дата выпуска')),
                ('expiration_date', models.DateField(help_text='Дата окончания срока')),
                ('slug', models.SlugField(blank=True, max_length=255, unique_for_date='created', validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('company', models.ForeignKey(help_text='Компания', on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='medicine.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
