# Generated by Django 4.0.2 on 2022-02-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='company',
            field=models.ForeignKey(help_text='Компания', on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicine.company'),
        ),
    ]
