# Generated by Django 4.0.2 on 2022-02-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique_for_date='created'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique_for_date='created'),
        ),
    ]
