# Generated by Django 4.0.2 on 2022-02-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_company_slug_alter_medicine_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Companies'},
        ),
    ]
